# Location refers to the login spot that players will be at when logging in

location:
  overworld:
    corner_1:
      x: -2.0
      y: 90
      z: -2.0
    corner_2:
      x: 2.0
      y: 94
      z: 2.0

  nether:
    corner_1:
      x: -2.0
      y: 0.0
      z: -2.0
    corner_2:
      x: 2.0
      y: 0.0
      z: 2.0

  end:
    corner_1:
      x: -2.0
      y: 0.0
      z: -2.0
    corner_2:
      x: 2.0
      y: 0.0
      z: 2.0

no_auth_should_glow: true