# Location refers to the login spot that players will be at when logging in

location:
  overworld:
    x: 0.0
    y: 90.0
    z: 0.0

  nether:
    x: 0.0
    y: 60.0
    z: 0.0

  end:
    x: 0.0
    y: 0.0
    z: 0.0
