name: PasswordLogOn
version: 1.3.1
main: me.awesomemoder316.passwordlogon.PasswordLogOn
author: Awesomemoder316
api-version: 1.14
commands:
  password:
    description: sets and resets password
    aliases: pw
    usage: /password [set/reset] [password] [new password if reset is chosen]